export * from './Adivinhação';
export * from './Alquimia';
export * from './Encantamento';
export * from './Elementarismo';
export * from './Feitiço';
export * from './Levitação';
export * from './Necromancia';
export * from './Teurgia';
export * from './Transmutação';
